export default {
    TYPES:{
        CHECKOUT:"checkout",
        SHIPPING:"shipping",
        ADDRESS:"address",
        DELIVERY:"delivery",
        PAYMENT:"payment",
        REVIEW:"review",
        PRICE:"price",
        CARDID:"cardId",
        ORDER_SUMMARY:"ordersummary",
        PLACE_ORDER:"placeorder",
        QUOTE:"quote",
        SIGN_UP:"signup",
        PROGRESS:"progress"
    },
    MSG:{
        
    },
    VIEW:{
        STATUS:{
            "HIDE":0,
            "SHOW":1,
            "UNINSTALL":2
        },
        TYPES:{
            USUALLY:"usually",
            POPUP:"popup"
        }
    }
}